### ISSUE TITLE
HOL Exercise 2 Task 4 - Register DataMigration Resource Provider

### ISSUE THREAD

**Issue by cassiejones444** [Microsoft/MCW-Azure-Migration#8]
Should this be the first task? Or even part of the pre-reqs?

Don't understand why you have something that takes a wee while to complete in the middle of the exercise.

Cassie

**Comment by jtuliani** [comment]
Moved to the first task in the exercise, good idea.

I think it's important that this is part of the HOL, and not in the pre-reqs. The students need to see it. Items in the pre-reqs may be automated by the lab platform (depending on what platform is used) and hence not seen by students.
